Initial external transport templates

diff --git a/templates/common/functions b/templates/common/functions
--- a/templates/common/functions
+++ b/templates/common/functions
@@ -393,3 +393,28 @@ start_olsr()
 
     olsrd -f "$routingconf" &> "$logfile"
 }
+
+start_emanetransportd()
+{
+    local node_name=$1
+    local xml=$2
+    local logfile=$3
+    local pidfile=$4
+    local uuidfile=$5
+
+    if [ -f $xml ]
+    then
+        echo "$node_name: starting emanetransportd: $xml"
+
+        emanetransportd -r -d "$xml" -l 3 -f "$logfile" \
+                         --pidfile "$pidfile" --uuidfile "$uuidfile"
+
+        retval=$?
+    else
+        echo "$node_name: missing emanetransportd XML: $xml"
+
+        retval=1
+    fi
+
+    return $retval
+}
